[build]
  command = "npx tailwindcss -i ./style.css -o ./dist/output.css && npm run build"
  publish = "dist"  # Ajusta esto según tu directorio de salida

[context.production.environment]
  NODE_ENV = "production"
